# Ansible managed: /ansible/roles/postgresql/templates/database.yml.j2 modified on 2015-09-29 12:24:39 by vagrant on localhost

default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: maecen

  username: vagrant
  password: None

test:
  <<: *default
  database: maecen_test
